apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: health-service-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-service
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        metricName: nginx_requests_per_second
        query: rate(nginx_ingress_controller_nginx_process_requests_total[1m])
        threshold: "10"
        activationThreshold: "0.5"
